---
- name: EC2 Facts
  ec2_instance_info:
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

    filters:
      instance-state-name: "running"
      "tag:Name": "{{config.instance_name}}"

  register: ec2
- debug: var=ec2

- name: Kill EC2 Instance
  ec2:
    instance_ids: "{{ ec2.instances[0].instance_id }}"
    state: "absent"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Retrieve the Records First
  route53:
    state: get
    zone: "{{ config.domain }}"
    record: "{{ config.instance_name }}.{{ config.domain }}"
    type: A
  register: rec

- name: display the record
  debug: var=rec

- name: Route 53 Delete Records
  route53:
    state: absent
    zone: "{{ config.domain }}"
    record: "{{ config.instance_name }}.{{ config.domain }}"
    type: "{{ rec.set.Type }}"
    ttl: "{{ rec.set.TTL }}"
    value: "{{ rec.set.ResourceRecords[0].Value }}"
    wait: yes
  register: result

- name: display results
  debug: var=result

- name: Remove host from known_hosts
  connection: local
  shell: "ssh-keygen -f ~/.ssh/known_hosts -R {{ config.instance_name }}.{{ config.domain }}"
# - name: Remove host from known_hosts
#   known_hosts:
#     path: ~/.ssh/known_hosts
#     name: "{{ config.instance_name }}.{{ config.domain }}"
#     state: "absent"
#   become: yes

# - name: Remove host from known_hosts
#   known_hosts:
#     path: ~/.ssh/known_hosts
#     name: "{{ ec2.instances[0].public_dns_name }}"
#     state: "absent"
#   become: yes
